# version: '3.8'  # Remove this line

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

  # jenkins:
  #   image: jenkins/jenkins:jdk17
  #   container_name: jenkins
  #   user: root
  #   ports:
  #     - "8080:8080"
  #     - "50000:50000" # For Jenkins agents
  #   volumes:
  #     - jenkins-data:/var/jenkins_home
  #     - /var/run/docker.sock:/var/run/docker.sock # Needed for Jenkins to run Docker commands
  #   environment:
  #     - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube-data:/var/lib/sonar

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100

volumes:
  grafana-data:
  jenkins-data:
  sonarqube-data:
